### ISSUE TITLE
on kali linux 2020

### ISSUE THREAD

**Issue by Skymord** [EntySec/ghost#200]
Traceback (most recent call last):
  File "./ghost", line 37, in <module>
    from core.server import server
  File "/home/kali/ghost/core/server.py", line 32, in <module>
    from core.ghost import ghost
  File "/home/kali/ghost/core/ghost.py", line 32, in <module>
    from core.transfer import transfer
ModuleNotFoundError: No module named 'core.transfer'

**Comment by enty8080** [comment]
This fixed, reinstall it. I mean run `uninstall.sh` and then git clone and `install.sh`
