### ISSUE TITLE
Gracefully exit on KeyboardInterrupt 

### ISSUE THREAD

**Issue by PSNAppz** [EntySec/ghost#253]
Right now, when we try `cntrl + c` or `KeyboardInterrupt`, it creates a mess.

<details>

```
^CTraceback (most recent call last):
  File "./ghost", line 124, in <module>
    main()
  File "./ghost", line 110, in main
    server.connect(rhost, rport)
  File "/Users/psn/.ghost/core/server.py", line 44, in connect
    self.ghost.start_server()
  File "/Users/psn/.ghost/core/ghost.py", line 48, in start_server
    self.send_command("start-server", "", False, False)
  File "/Users/psn/.ghost/core/ghost.py", line 43, in send_command
    command_output = subprocess.getoutput("adb " + command + " " + arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 630, in getoutput
    return getstatusoutput(cmd)[1]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 611, in getstatusoutput
    data = check_output(cmd, shell=True, text=True, stderr=STDOUT)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 951, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt
```
<summary>
Like this:
</summary>
</details>

**Comment by PSNAppz** [comment]
I want to work on this issue.
