### ISSUE TITLE
NO module named ghost.core

### ISSUE THREAD

**Issue by excep** [EntySec/Ghost#313]
#python3 ghost.py

Traceback (most recent call last):
  File "/home/nouaman/GITHUB/Ghost/ghost/ghost.py", line 31, in <module>
    from ghost.core.base.console import Console
  File "/home/nouaman/GITHUB/Ghost/ghost/ghost.py", line 31, in <module>
    from ghost.core.base.console import Console
ModuleNotFoundError: No module named 'ghost.core'; 'ghost' is not a package

**Comment by enty8080** [comment]
`pip3 install git+https://github.com/EntySec/Ghost`
