### ISSUE TITLE
unable to complete installation

### ISSUE THREAD

**Issue by GITS2029** [EntySec/Ghost#354]
$ ghost
Traceback (most recent call last):
  File "/usr/local/bin/ghost", line 33, in <module>
    sys.exit(load_entry_point('ghost==8.0.0', 'console_scripts', 'ghost')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ghost", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/ghost-8.0.0-py3.11.egg/ghost/__init__.py", line 25, in <module>
    from ghost.core.base.console import Console
  File "/usr/local/lib/python3.11/dist-packages/ghost-8.0.0-py3.11.egg/ghost/core/base/console.py", line 28, in <module>
    from ghost.core.base.device import Device
  File "/usr/local/lib/python3.11/dist-packages/ghost-8.0.0-py3.11.egg/ghost/core/base/device.py", line 37, in <module>
    from pex.fs import FS
ModuleNotFoundError: No module named 'pex.fs'
                                                                             
┌──(git5㉿kali)-[~/Desktop/tools/Ghost/ghost]
└─$ sudo ghost
Traceback (most recent call last):
  File "/usr/local/bin/ghost", line 33, in <module>
    sys.exit(load_entry_point('ghost==8.0.0', 'console_scripts', 'ghost')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ghost", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/ghost-8.0.0-py3.11.egg/ghost/__init__.py", line 25, in <module>
    from ghost.core.base.console import Console
  File "/usr/local/lib/python3.11/dist-packages/ghost-8.0.0-py3.11.egg/ghost/core/base/console.py", line 28, in <module>
    from ghost.core.base.device import Device
  File "/usr/local/lib/python3.11/dist-packages/ghost-8.0.0-py3.11.egg/ghost/core/base/device.py", line 37, in <module>
    from pex.fs import FS
ModuleNotFoundError: No module named 'pex.fs'

**Comment by enty8080** [comment]
`pip3 uninstall pex`, `pip3 install git+https://github.com/entysec/pex`
