### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by s3cur3c1ph3r** [EntySec/Ghost#373]
──(root㉿kali)-[~]
└─# ghost                                                            
Traceback (most recent call last):
  File "/usr/local/bin/ghost", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghost/__init__.py", line 35, in cli
    console.shell()
  File "/usr/local/lib/python3.11/dist-packages/ghost/core/console.py", line 225, in shell
    self.badges.print_empty(self.banner, translate=False)
  File "/usr/local/lib/python3.11/dist-packages/badges/__main__.py", line 44, in print_empty
    self.print(*args, **kwargs)
TypeError: IO.print() got an unexpected keyword argument 'translate'

**Comment by enty8080** [comment]
Fixed, please reinstall
